// contants of app
const int ERROR_CODE_UNABLE_TO_COMMUNICATE_WITH_THE_SERVER = 1;
const int ERROR_CODE_UNEXPECTED_ERROR = 2;
const int ERROR_CODE_SERVER_PUBLIC_KEY_IS_UNKNOWN = 3;
const int ERROR_CODE_USER_NOT_AUTHENTICATED = 4;
const int ERROR_CODE_DID_NOT_POSSIBLE_DECRYPTED_SERVER_RESPONSE = 5;
const int ERROR_CODE_WITHOUT_INTERNET_CONNECTION = 6;

// constants of server
const int ERROR_CODE_INSUFFICIENT_DATA_PROVIDED = 100;
const int ERROR_CODE_NO_RESULT_FOUND = 103;
const int ERROR_CODE_SAVE_FAILURE = 104;
const int ERROR_CODE_REMOVAL_FAILURE = 105;
const int ERROR_CODE_USER_ALREADY_REGISTERED = 110;
const int ERROR_CODE_REVISE_DATA_INFORMED = 111;
const int ERROR_CODE_INVALID_PIN_CODE = 112;
const int ERROR_CODE_UNEXPECTED_ERROR_IN_SERVER = 113;
const int ERROR_CODE_UNABLE_TO_CREATE_AN_ACCOUNT = 114;
const int ERROR_CODE_INVALID_QR_CODE = 115;
const int ERROR_CODE_FAILED_PRIVACY_LEVEL_UPDATE = 116;
const int ERROR_CODE_EMAIL_IS_ALREADY_IN_USE = 117;
const int ERROR_CODE_INVALID_CONFIRMATION_CODE = 118;
const int ERROR_CODE_UNABLE_RECOVER_ACCOUNT = 119;
